# Generated by Django 3.2.16 on 2023-11-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('user',), 'verbose_name': 'подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
